<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dewiride.Analytics.Classification.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dewiride.Analytics.Classification\Dewiride.Analytics.Classification.csproj" />
  </ItemGroup>

</Project>
