namespace Dewiride.Analytics.Domain.Telemetry;

/// <summary>
/// One observation of activity on a customer's site, as accepted by the collector and
/// written to the telemetry store.
/// </summary>
/// <remarks>
/// <para>
/// Two timestamps are carried deliberately. <see cref="ServerTimestamp"/> is stamped by the
/// collector and is the only one any query may order or bucket by.
/// <see cref="ClientTimestamp"/> is whatever the client claimed and is never trusted — it
/// exists so that <see cref="ClockSkewMs"/> can be derived, which is itself a
/// classification feature: automation frequently runs on hosts whose clocks are either
/// perfectly synchronised or wildly wrong, and both are informative.
/// </para>
/// <para>
/// Field-level privacy notes are on the individual members. The envelope is defined in
/// <c>docs/adr/0005-privacy-envelope.md</c>: the raw address is retained for 72 hours to
/// permit investigation and is then dropped, leaving only the derived network attributes.
/// </para>
/// </remarks>
public sealed record RawEvent
{
    /// <summary>
    /// Identity of this event, generated by the collector as a UUIDv7 so that it sorts by
    /// creation time and can be used to make ingestion idempotent under client retry.
    /// </summary>
    public required Guid EventId { get; init; }

    /// <summary>The site this event belongs to. Every query is scoped by this.</summary>
    public required Guid SiteId { get; init; }

    /// <summary>What the event records.</summary>
    public required EventKind Kind { get; init; }

    /// <summary>Which capture surface observed it.</summary>
    public required IngestSurface Surface { get; init; }

    /// <summary>Authoritative time, stamped by the collector on receipt.</summary>
    public required DateTimeOffset ServerTimestamp { get; init; }

    /// <summary>
    /// Time the client claimed, if it supplied one. Untrusted; retained only to derive
    /// <see cref="ClockSkewMs"/>.
    /// </summary>
    public DateTimeOffset? ClientTimestamp { get; init; }

    /// <summary>
    /// Difference between the client's claimed time and the collector's, in milliseconds.
    /// Zero when the client supplied no timestamp.
    /// </summary>
    public int ClockSkewMs { get; init; }

    /// <summary>
    /// Opaque per-visitor key. Derived by hashing coarse request attributes together with a
    /// salt that rotates every day, so it groups a visitor's activity within one day and
    /// cannot link them across days. Null when the surface cannot compute one.
    /// </summary>
    public string? VisitorKey { get; init; }

    /// <summary>Host the request was made against, lower-cased.</summary>
    public required string Host { get; init; }

    /// <summary>Path component of the requested URL, without query string.</summary>
    public required string Path { get; init; }

    /// <summary>Query string, retained without its values where the site opts out.</summary>
    public string? QueryString { get; init; }

    /// <summary>Full referring URL as supplied, or null when absent.</summary>
    public string? Referrer { get; init; }

    /// <summary>Registrable domain of <see cref="Referrer"/>, pre-computed for grouping.</summary>
    public string? ReferrerDomain { get; init; }

    /// <summary>Raw user-agent string. Attacker-controlled: never interpolate into SQL or a model prompt.</summary>
    public string? UserAgent { get; init; }

    /// <summary>
    /// HTTP status code the site returned. Only the server-side and log-import surfaces can
    /// observe this, and it is how security scanners are identified — they are recognised
    /// almost entirely by streams of requests to paths that do not exist.
    /// </summary>
    public short? StatusCode { get; init; }

    /// <summary>Response content type, where the surface can observe it.</summary>
    public string? ContentType { get; init; }

    /// <summary>Bytes sent in the response, where observable. Feeds resource-consumption reporting.</summary>
    public long? ResponseBytes { get; init; }

    /// <summary>
    /// Visitor's network address. Personal data: retained for 72 hours, then nulled by the
    /// retention job once the derived network attributes have been resolved from it.
    /// </summary>
    public string? IpAddress { get; init; }

    /// <summary>Browser viewport width in CSS pixels, where the surface can observe it.</summary>
    public int? ViewportWidth { get; init; }

    /// <summary>Browser viewport height in CSS pixels, where the surface can observe it.</summary>
    public int? ViewportHeight { get; init; }

    /// <summary>Primary language the client declared.</summary>
    public string? Language { get; init; }

    /// <summary>Client's UTC offset in minutes, where declared.</summary>
    public short? TimezoneOffsetMinutes { get; init; }

    /// <summary>
    /// Engaged time on the page in milliseconds, accumulated only while the tab was
    /// actually visible. Present on <see cref="EventKind.Engagement"/> and
    /// <see cref="EventKind.Exit"/> events.
    /// </summary>
    public int? EngagedMs { get; init; }

    /// <summary>Furthest scroll depth reached, as a percentage of document height.</summary>
    public byte? ScrollDepthPercent { get; init; }

    /// <summary>
    /// Whether any pointer interaction occurred. Presence only — never coordinates.
    /// </summary>
    public bool? HadPointerInteraction { get; init; }

    /// <summary>
    /// Whether any keyboard interaction occurred. Presence only — never key identities and
    /// never typed content. Knowing that a person typed is useful; knowing what they typed
    /// is surveillance this product does not do.
    /// </summary>
    public bool? HadKeyboardInteraction { get; init; }

    /// <summary>
    /// Whether the client reported itself as being under automation control. Trivially
    /// falsifiable, so it is treated as one weak signal among many rather than a verdict.
    /// </summary>
    public bool? DeclaredWebDriver { get; init; }

    /// <summary>
    /// Correlation identifier stamped into the served HTML by a server-side surface, echoed
    /// back by the browser tracker. When HTML was served under an identifier that no script
    /// ever reported, the page was fetched but never rendered — which is itself evidence.
    /// </summary>
    public string? CorrelationId { get; init; }
}
