using System.Collections.Frozen;

namespace Dewiride.Analytics.Classification;

/// <summary>
/// Which way a piece of evidence points.
/// </summary>
public enum SignalDirection
{
    /// <summary>Supports the session having been generated by a person.</summary>
    TowardHuman = -1,

    /// <summary>Neither supports nor opposes; carries context only.</summary>
    Neutral = 0,

    /// <summary>Supports the session having been generated by automation.</summary>
    TowardAutomation = 1,
}

/// <summary>
/// One observation a detector made about a session, with the weight it carries.
/// </summary>
/// <remarks>
/// <para>
/// A signal never contains prose. It carries a stable <see cref="Code"/> and the values
/// needed to render it, and the user-facing sentence is produced by looking that code up in
/// the message catalogue. This is what makes the evidence explanation translatable, testable
/// and stable across releases: the sentence can be rewritten in twelve languages without
/// touching the detector, and a golden-fixture snapshot compares codes rather than English.
/// </para>
/// <para>
/// It is also what keeps the explanation honest. Detectors cannot editorialise, because they
/// have nowhere to put an adjective.
/// </para>
/// </remarks>
public sealed record Signal
{
    /// <summary>
    /// Stable identifier for this observation, in dotted lower-case, for example
    /// <c>traversal.sitemap_order</c>. Doubles as the message-catalogue key. Once published
    /// it must not be reused for a different meaning, because stored classifications
    /// reference it.
    /// </summary>
    public required string Code { get; init; }

    /// <summary>Which way this evidence points.</summary>
    public required SignalDirection Direction { get; init; }

    /// <summary>
    /// Relative weight, from 0 (mentioned but not counted) to 100 (decisive on its own).
    /// These are informed priors, not fitted coefficients — see <see cref="EvidenceStrength"/>.
    /// </summary>
    public required int Weight { get; init; }

    /// <summary>
    /// Values substituted into the rendered sentence, for example
    /// <c>{ "pageCount": 42, "seconds": 83 }</c>. Keys are referenced by the message template.
    /// </summary>
    public FrozenDictionary<string, string> Parameters { get; init; } =
        FrozenDictionary<string, string>.Empty;
}
